version: '3.8'

services:
  db:
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: ca_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: auction_db
      MYSQL_USER: auction_user
      MYSQL_PASSWORD: StrongP@ssw0rd!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_DSN: auction_user:StrongP@ssw0rd!@tcp(db:3306)/auction_db?parseTime=True
      JWT_SECRET: test-secret
      AUCTION_TTL_MINUTES: "60"
    ports:
      - "8080:8080"
    command: ["go","run","./cmd/server"]
    volumes:
      - ./uploads:/app/uploads

volumes:
  db_data:
